language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
script:
  - python manage.py test
after_success: coveralls
