language: python
python:
  - "3.5"
before_install:
  - cp contrib/.env.sample .env
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py test
after_success: coveralls
