language: python
sudo: false
branches:
  only:
    - master
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - npm install
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --no-input
script:
  - python manage.py test -v 3
after_success:
  - coveralls
