language: python
sudo: false
branches:
  only:
    - master
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - npm install
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --no-input
script:
  - coverage run --source=valentina manage.py test -v 3
after_success:
  - coveralls
addons:
  code_climate:
    repo_token: 85edc29b4d5e984373358286806b91c285891c3d0279d2fe6605cf074e4aec1e
