# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, verbose_name='gênero')),
                ('timezone', models.CharField(max_length=255, verbose_name='fuso-horário')),
                ('nickname', models.CharField(max_length=255, verbose_name='apelido')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'ordering': ['nickname'],
                'verbose_name_plural': 'usuárias',
                'verbose_name': 'usuária',
            },
        ),
    ]
