# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['nickname'], 'verbose_name': 'usuária', 'verbose_name_plural': 'usuárias'},
        ),
        migrations.AddField(
            model_name='profile',
            name='first_access',
            field=models.BooleanField(default=True, verbose_name='primeiro acesso'),
        ),
    ]
