# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20160228_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=140, verbose_name='Nome fictício')),
            ],
            options={
                'verbose_name': 'afiliação',
                'verbose_name_plural': 'afiliações',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=255, verbose_name='identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'chat',
                'verbose_name_plural': 'chats',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
            },
        ),
        migrations.AddField(
            model_name='affiliation',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Chat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuária'),
        ),
    ]
