# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160228_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(null=True, verbose_name='conteúdo'),
        ),
    ]
