# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 23:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Chat'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuária'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuária'),
        ),
    ]
