# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160303_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'mensagem', 'verbose_name_plural': 'mensagens'},
        ),
    ]
