# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160306_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook access token'),
        ),
    ]
