# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='bloqueada'),
        ),
    ]
