# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Janela aberta'),
        ),
    ]
